/*
 * ADC_NTI_Interface.h
 *
 *  Created on: Oct 23, 2023
 *      Author: AHMED
 */

#ifndef MCAL_ADC_NTI_ADC_CONFIG_H_
#define MCAL_ADC_NTI_ADC_CONFIG_H_

/*
 * DIVIDE_BY_2
 * DIVIDE_BY_4
 * DIVIDE_BY_8
 * DIVIDE_BY_16
 * DIVIDE_BY_32
 * DIVIDE_BY_64
 * DIVIDE_BY_128
 *
*/

#define ADC_PRESCALER_SELECTION 	DIVIDE_BY_128


#define ADC_AUTO_TRIGGER_MODE		NORMAL_MODE
/*
 *
 */
#define ADJUSTMENT				RIGHT_ADJUSTMENT

#define VOLTAGE_REFERENCE			AVCC

#endif /* MCAL_ADC_NTI_ADC_CONFIG_H_ */
